# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/axi_gpio_js/axi_gpio_js.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_js || ORIG_REF_NAME==axi_gpio_js} -quiet] -quiet

# IP: bd/axi_gpio_js/ip/axi_gpio_js_processing_system7_0_0/axi_gpio_js_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_js_processing_system7_0_0 || ORIG_REF_NAME==axi_gpio_js_processing_system7_0_0} -quiet] -quiet

# IP: bd/axi_gpio_js/ip/axi_gpio_js_axi_gpio_0_0/axi_gpio_js_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_js_axi_gpio_0_0 || ORIG_REF_NAME==axi_gpio_js_axi_gpio_0_0} -quiet] -quiet

# IP: bd/axi_gpio_js/ip/axi_gpio_js_xbar_0/axi_gpio_js_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_js_xbar_0 || ORIG_REF_NAME==axi_gpio_js_xbar_0} -quiet] -quiet

# IP: bd/axi_gpio_js/ip/axi_gpio_js_ps7_0_axi_periph_0/axi_gpio_js_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_js_ps7_0_axi_periph_0 || ORIG_REF_NAME==axi_gpio_js_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/axi_gpio_js/ip/axi_gpio_js_rst_ps7_0_50M_0/axi_gpio_js_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_js_rst_ps7_0_50M_0 || ORIG_REF_NAME==axi_gpio_js_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/axi_gpio_js/ip/axi_gpio_js_axi_gpio_1_1/axi_gpio_js_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_js_axi_gpio_1_1 || ORIG_REF_NAME==axi_gpio_js_axi_gpio_1_1} -quiet] -quiet

# IP: bd/axi_gpio_js/ip/axi_gpio_js_axi_gpio_2_1/axi_gpio_js_axi_gpio_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_js_axi_gpio_2_1 || ORIG_REF_NAME==axi_gpio_js_axi_gpio_2_1} -quiet] -quiet

# IP: bd/axi_gpio_js/ip/axi_gpio_js_auto_pc_0/axi_gpio_js_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_js_auto_pc_0 || ORIG_REF_NAME==axi_gpio_js_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/jayde/axi_gpio_js/axi_gpio_js.gen/sources_1/bd/axi_gpio_js/axi_gpio_js_ooc.xdc
