# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jayde/axi_gpio_js/axi_gpio_js.srcs/sources_1/bd/axi_gpio_js/ip/axi_gpio_js_rst_ps7_0_50M_0/axi_gpio_js_rst_ps7_0_50M_0.xci
# IP: The module: 'axi_gpio_js_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jayde/axi_gpio_js/axi_gpio_js.gen/sources_1/bd/axi_gpio_js/ip/axi_gpio_js_rst_ps7_0_50M_0/axi_gpio_js_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_js_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jayde/axi_gpio_js/axi_gpio_js.gen/sources_1/bd/axi_gpio_js/ip/axi_gpio_js_rst_ps7_0_50M_0/axi_gpio_js_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_js_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jayde/axi_gpio_js/axi_gpio_js.gen/sources_1/bd/axi_gpio_js/ip/axi_gpio_js_rst_ps7_0_50M_0/axi_gpio_js_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_js_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/jayde/axi_gpio_js/axi_gpio_js.srcs/sources_1/bd/axi_gpio_js/ip/axi_gpio_js_rst_ps7_0_50M_0/axi_gpio_js_rst_ps7_0_50M_0.xci
# IP: The module: 'axi_gpio_js_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jayde/axi_gpio_js/axi_gpio_js.gen/sources_1/bd/axi_gpio_js/ip/axi_gpio_js_rst_ps7_0_50M_0/axi_gpio_js_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_js_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jayde/axi_gpio_js/axi_gpio_js.gen/sources_1/bd/axi_gpio_js/ip/axi_gpio_js_rst_ps7_0_50M_0/axi_gpio_js_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_js_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jayde/axi_gpio_js/axi_gpio_js.gen/sources_1/bd/axi_gpio_js/ip/axi_gpio_js_rst_ps7_0_50M_0/axi_gpio_js_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_js_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
